# Numpy

In [8]:
# https://blog.csdn.net/Refrain__WG/article/details/88423463
# numpy 学习笔记（博客）

In [5]:
# ndarray与Python原生list运算效率对比
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr2 = my_arr *2

CPU times: user 20.2 ms, sys: 9.66 ms, total: 29.8 ms
Wall time: 30.1 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 719 ms, sys: 205 ms, total: 925 ms
Wall time: 926 ms


In [10]:
# numpy 多维数组: ndarray
data = np.random.randn(2, 3)
data

array([[ 0.56091305, -1.45599   ,  0.85476623],
       [-0.64314189, -0.24612681, -0.3756259 ]])

In [11]:
data * 10

array([[  5.60913049, -14.55989996,   8.54766226],
       [ -6.43141886,  -2.46126815,  -3.756259  ]])

In [12]:
data + data

array([[ 1.1218261 , -2.91197999,  1.70953245],
       [-1.28628377, -0.49225363, -0.7512518 ]])

In [13]:
# ndarray的属性 & 类型
# ndarray.shape:  数组维度的元组,  
# ndarray.size:   数组中的元素数量, 
# ndarray.dtype:  数组元素的类型   -- np.int64/np.int32/np.float64/np.float32/np.string_/np.unicode_/np.bool ...
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

In [15]:
# 生成0和1的数组 -- zeros(shape[, dtype, order]), ones(shape[, dtype, order])
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((2, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])